inventorysystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('', include('user.urls')),

]

product/urls.py
# product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'), # 127.0.0.1:8000 과 views.py 폴더의 home 함수 연결
    path('product/', views.product, name='product'), # 127.0.0.1:8000/product 과 views.py 폴더의 product 함수 연결
    path('add/', views.add_product, name='add_product'),
    path('add_quantity/', views.add_quantity, name='add_quantity'),
    path('remove_quantity/', views.remove_quantity, name='remove_quantity'),
    path('total_quantity/', views.total_quantity, name='total_quantity'),
    path('product_list/', views.product_list, name='product_list'),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.sign_in_view, name='sign-in'),
    path('sign-up/', views.sign_up_view, name='sign-up'),
    path('sign-in/', views.sign_in_view, name='sign-in'),
    path('logout/', views.logout, name='logout'),
]

product/models.py
# product/models.py
from django.db import models
from user.models import UserModel
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models

default_value = timezone.now()

# Create your models here.


class Product(models.Model):
    class Meta:
        db_table = "product"

    code = models.CharField(max_length=50, unique=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    kind = models.CharField(max_length=50)
    quantity = models.IntegerField(default=0)

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.http import HttpResponseNotAllowed
from django.http import JsonResponse
from django.db.models import Sum

# Create your views here.


def home(request):
    user = request.user.is_authenticated
    if user:
        return redirect('/product')
    else:
        return redirect('/sign-in')


def product(request):
    if request.method == 'GET':
        user = request.user.is_authenticated

        if user:
            products = Product.objects.all().values('code', 'kind', 'quantity')
            total = products.aggregate(Sum('quantity'))['quantity__sum'] or 0
            context = {"products": list(products), "total": total}
            return render(request, 'product/home.html', context)
        else:
            return redirect('/sign-in')



def add_product(request):
    if request.method == "POST":
        kind = request.POST.get("kind")
        if kind == "hoodie_s":
            code = "HDS"
        elif kind == "hoodie_m":
            code = "HDM"
        elif kind == "hoodie_l":
            code = "HDL"
        elif kind == "jeans_free":
            code = "JNF"
        elif kind =="socks_free":
            code == "SOK"
        elif kind =="hat_free":
            code = "HAT"
        else:
            message = "잘못된 상품 코드입니다. 다시 입력해주세요."
            context = {"message": message}
            return render(request, "product/home.html", context)

        quantity = request.POST.get("quantity")
        if not quantity:
            message = "수량을 입력해주세요."
            context = {"message": message}
            return render(request, "product/home.html", context)

        product = Product(code=code, kind=kind, quantity=quantity, author=request.user)
        product.save()
        message = f"{product} 상품이 등록되었습니다."
        context = {"message": message}
        return render(request, "product/home.html", context)
    else:
        return render(request, "product/home.html")





    
@csrf_exempt
def add_quantity(request):
    if request.method == "POST":
        kind = request.POST.get("kind")
        quantity = int(request.POST.get("quantity"))
        if kind == "hoodie_s":
            code = "HDS"
        elif kind == "hoodie_m":
            code = "HDM"
        elif kind == "hoodie_l":
            code = "HDL"
        elif kind == "jeans_free":
            code = "JNF"
        elif kind =="socks_free":
            code == "SOK"
        elif kind =="hat_free":
            code = "HAT"
        else:
            message = "잘못된 상품 코드입니다. 다시 입력해주세요."
            context = {"message": message}
            print(kind)
            return render(request, "product/home.html", context)

        product, created = Product.objects.get_or_create(code=code, defaults={"kind": kind, "author": request.user})
        product.quantity += quantity
        product.save()
        message = f"{product} 상품에 {quantity}개가 입고되었습니다."
        context = {"message": message}
        return render(request, "product/home.html", context)
    else:
        return render(request, "product/home.html")




def remove_quantity(request):
    if request.method == "POST":
        kind = request.POST.get("kind")
        quantity = int(request.POST.get("quantity"))

        if kind == "hoodie_s":
            code = "HDS"
        elif kind == "hoodie_m":
            code = "HDM"
        elif kind == "hoodie_l":
            code = "HDL"
        elif kind == "jeans_free":
            code = "JNF"
        elif kind =="socks_free":
            code == "SOK"
        elif kind =="hat_free":
            code = "HAT"
        else:
            message = "잘못된 상품 코드입니다. 다시 입력해주세요."
            context = {"message": message}
            return render(request, "product/home.html", context)

        product = Product.objects.get(code=code)
        if product.quantity >= quantity:
            product.quantity -= quantity
            product.save()
            message = f"{product} 상품에 {quantity}개가 출고되었습니다."
        else:
            message = f"{product} 상품의 재고가 부족합니다."
        context = {"message": message}
        return render(request, "product/home.html", context)
    else:
        return render(request, "product/home.html")



def total_quantity(request):
    total = Product.objects.aggregate(Sum("quantity"))["quantity__sum"]
    if total is None:
        total = 0
    return JsonResponse({"total": total})




def product_list(request):
    products = Product.objects.all().values('code', 'kind', 'quantity')
    total = products.aggregate(Sum('quantity'))['quantity__sum'] or 0
    context = {"products": list(products), "total": total}
    return render(request, "product/home.html", context)

templates/product/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <h2>상품 추가</h2>
      <form method="post" action="{% url 'product:add_product' %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="kind">종류:</label>
          <select class="form-control" id="kind" name="kind" required>
            <option value="hoodie_s">후드티 S</option>
            <option value="hoodie_m">후드티 M</option>
            <option value="hoodie_l">후드티 L</option>
            <option value="jeans_free">청바지 Free</option>
            <option value="socks_free">양말</option>
            <option value="hat_free">모자</option>
          </select>
        </div>
        <button type="submit" class="btn btn-primary">추가</button>
      </form>
    </div>
    <div class="col-md-4">
      <h2>상품 입고</h2>
      <form method="post" action="{% url 'product:add_quantity' %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="code">코드:</label>
          <select class="form-control" id="code" name="kind" required>
            <option value="hoodie_s">후드티 S</option>
            <option value="hoodie_m">후드티 M</option>
            <option value="hoodie_l">후드티 L</option>
            <option value="jeans_free">청바지</option>
            <option value="socks_free">양말</option>
            <option value="hat_free">모자</option>
          </select>
        </div>
        <div class="form-group">
          <label for="quantity">수량:</label>
          <input type="number" class="form-control" id="quantity" name="quantity" required>
        </div>
        <button type="submit" class="btn btn-primary">입고</button>
      </form>
    </div>
    <div class="col-md-4">
      <h2>상품 출고</h2>
      <form method="post" action="{% url 'product:remove_quantity' %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="kind">종류:</label>
          <select class="form-control" id="kind" name="kind" required>
            <option value="hoodie_s">후드티 S</option>
            <option value="hoodie_m">후드티 M</option>
            <option value="hoodie_l">후드티 L</option>
            <option value="jeans_free">청바지</option>
            <option value="socks_free">양말</option>
            <option value="hat_free">모자</option>
          </select>
        </div>
        <div class="form-group">
          <label for="quantity">수량:</label>
          <input type="number" class="form-control" id="quantity" name="quantity" required>
        </div>
        <button type="submit" class="btn btn-primary">출고</button>
      </form>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="text-center">전체 재고</h2>
        <p class="text-center">전체 재고 수량: {{ total|default:0 }}</p>
    </div>
    
    </div>    
    <hr>
    
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 text-center">
          <h2>상품 리스트</h2>
          <table class="table" style="font-size: 18px;">
            <thead>
              <tr>
                <th>코드</th>
                <th>종류</th>
                <th>수량</th>
              </tr>
            </thead>
            <tbody>
              {% for product in products %}
              <tr>
                <td>{{ product.code }}</td>
                <td>{{ product.kind }}</td>
                <td>{{ product.quantity }}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="3">등록된 상품이 없습니다.</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  {%endblock%}
    